<?php
/**
 * ConnectorSource
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ragie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConnectorSource Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectorSource
{
    /**
     * Possible values of this enum
     */
    public const BACKBLAZE = 'backblaze';

    public const CONFLUENCE = 'confluence';

    public const DROPBOX = 'dropbox';

    public const FRESHDESK = 'freshdesk';

    public const ONEDRIVE = 'onedrive';

    public const GOOGLE_DRIVE = 'google_drive';

    public const GMAIL = 'gmail';

    public const INTERCOM = 'intercom';

    public const NOTION = 'notion';

    public const SALESFORCE = 'salesforce';

    public const SHAREPOINT = 'sharepoint';

    public const JIRA = 'jira';

    public const SLACK = 'slack';

    public const S3 = 's3';

    public const GCS = 'gcs';

    public const HUBSPOT = 'hubspot';

    public const WEBCRAWLER = 'webcrawler';

    public const ZENDESK = 'zendesk';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BACKBLAZE,
            self::CONFLUENCE,
            self::DROPBOX,
            self::FRESHDESK,
            self::ONEDRIVE,
            self::GOOGLE_DRIVE,
            self::GMAIL,
            self::INTERCOM,
            self::NOTION,
            self::SALESFORCE,
            self::SHAREPOINT,
            self::JIRA,
            self::SLACK,
            self::S3,
            self::GCS,
            self::HUBSPOT,
            self::WEBCRAWLER,
            self::ZENDESK
        ];
    }
}


