<?php
/**
 * PartitionLimitExceededWebhookPayload
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ragie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PartitionLimitExceededWebhookPayload Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PartitionLimitExceededWebhookPayload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PartitionLimitExceededWebhookPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'partition' => 'string',
        'limit_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'partition' => null,
        'limit_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'partition' => false,
        'limit_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'partition' => 'partition',
        'limit_type' => 'limit_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'partition' => 'setPartition',
        'limit_type' => 'setLimitType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'partition' => 'getPartition',
        'limit_type' => 'getLimitType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const LIMIT_TYPE_PAGES_PROCESSED_LIMIT_MONTHLY = 'pages_processed_limit_monthly';
    public const LIMIT_TYPE_PAGES_HOSTED_LIMIT_MONTHLY = 'pages_hosted_limit_monthly';
    public const LIMIT_TYPE_PAGES_PROCESSED_LIMIT_MAX = 'pages_processed_limit_max';
    public const LIMIT_TYPE_PAGES_HOSTED_LIMIT_MAX = 'pages_hosted_limit_max';
    public const LIMIT_TYPE_VIDEO_PROCESSED_LIMIT_MONTHLY = 'video_processed_limit_monthly';
    public const LIMIT_TYPE_VIDEO_PROCESSED_LIMIT_MAX = 'video_processed_limit_max';
    public const LIMIT_TYPE_AUDIO_PROCESSED_LIMIT_MONTHLY = 'audio_processed_limit_monthly';
    public const LIMIT_TYPE_AUDIO_PROCESSED_LIMIT_MAX = 'audio_processed_limit_max';
    public const LIMIT_TYPE_MEDIA_STREAMED_LIMIT_MONTHLY = 'media_streamed_limit_monthly';
    public const LIMIT_TYPE_MEDIA_STREAMED_LIMIT_MAX = 'media_streamed_limit_max';
    public const LIMIT_TYPE_MEDIA_HOSTED_LIMIT_MONTHLY = 'media_hosted_limit_monthly';
    public const LIMIT_TYPE_MEDIA_HOSTED_LIMIT_MAX = 'media_hosted_limit_max';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLimitTypeAllowableValues()
    {
        return [
            self::LIMIT_TYPE_PAGES_PROCESSED_LIMIT_MONTHLY,
            self::LIMIT_TYPE_PAGES_HOSTED_LIMIT_MONTHLY,
            self::LIMIT_TYPE_PAGES_PROCESSED_LIMIT_MAX,
            self::LIMIT_TYPE_PAGES_HOSTED_LIMIT_MAX,
            self::LIMIT_TYPE_VIDEO_PROCESSED_LIMIT_MONTHLY,
            self::LIMIT_TYPE_VIDEO_PROCESSED_LIMIT_MAX,
            self::LIMIT_TYPE_AUDIO_PROCESSED_LIMIT_MONTHLY,
            self::LIMIT_TYPE_AUDIO_PROCESSED_LIMIT_MAX,
            self::LIMIT_TYPE_MEDIA_STREAMED_LIMIT_MONTHLY,
            self::LIMIT_TYPE_MEDIA_STREAMED_LIMIT_MAX,
            self::LIMIT_TYPE_MEDIA_HOSTED_LIMIT_MONTHLY,
            self::LIMIT_TYPE_MEDIA_HOSTED_LIMIT_MAX,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('partition', $data ?? [], null);
        $this->setIfExists('limit_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['partition'] === null) {
            $invalidProperties[] = "'partition' can't be null";
        }
        if ($this->container['limit_type'] === null) {
            $invalidProperties[] = "'limit_type' can't be null";
        }
        $allowedValues = $this->getLimitTypeAllowableValues();
        if (!is_null($this->container['limit_type']) && !in_array($this->container['limit_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'limit_type', must be one of '%s'",
                $this->container['limit_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets partition
     *
     * @return string
     */
    public function getPartition()
    {
        return $this->container['partition'];
    }

    /**
     * Sets partition
     *
     * @param string $partition partition
     *
     * @return self
     */
    public function setPartition($partition)
    {
        if (is_null($partition)) {
            throw new \InvalidArgumentException('non-nullable partition cannot be null');
        }
        $this->container['partition'] = $partition;

        return $this;
    }

    /**
     * Gets limit_type
     *
     * @return string
     */
    public function getLimitType()
    {
        return $this->container['limit_type'];
    }

    /**
     * Sets limit_type
     *
     * @param string $limit_type limit_type
     *
     * @return self
     */
    public function setLimitType($limit_type)
    {
        if (is_null($limit_type)) {
            throw new \InvalidArgumentException('non-nullable limit_type cannot be null');
        }
        $allowedValues = $this->getLimitTypeAllowableValues();
        if (!in_array($limit_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'limit_type', must be one of '%s'",
                    $limit_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['limit_type'] = $limit_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


