<?php

/**
 * DocumentsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ragie API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentsApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDocument
     *
     * Create Document.
     *
     */
    public function testCreateDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createDocumentFromUrl
     *
     * Create Document From Url.
     *
     */
    public function testCreateDocumentFromUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createDocumentRaw
     *
     * Create Document Raw.
     *
     */
    public function testCreateDocumentRaw()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDocument
     *
     * Delete Document.
     *
     */
    public function testDeleteDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocument
     *
     * Get Document.
     *
     */
    public function testGetDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentChunk
     *
     * Get Document Chunk.
     *
     */
    public function testGetDocumentChunk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentChunkContent
     *
     * Get Document Chunk Content.
     *
     */
    public function testGetDocumentChunkContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentChunks
     *
     * Get Document Chunks.
     *
     */
    public function testGetDocumentChunks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentContent
     *
     * Get Document Content.
     *
     */
    public function testGetDocumentContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentSource
     *
     * Get Document Source.
     *
     */
    public function testGetDocumentSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentSummary
     *
     * Get Document Summary.
     *
     */
    public function testGetDocumentSummary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listDocuments
     *
     * List Documents.
     *
     */
    public function testListDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchDocumentMetadata
     *
     * Patch Document Metadata.
     *
     */
    public function testPatchDocumentMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDocumentFile
     *
     * Update Document File.
     *
     */
    public function testUpdateDocumentFile()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDocumentFromUrl
     *
     * Update Document Url.
     *
     */
    public function testUpdateDocumentFromUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDocumentRaw
     *
     * Update Document Raw.
     *
     */
    public function testUpdateDocumentRaw()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
